[build-system]
requires = ['setuptools>=42.0','wheel']
build_backend = 'setuptools.build_meta'

[tools.pytest.ini_options]
testpaths = [
    "tests"
]

[tools.mypy]
mypypath = 'src'
ignore_missing_packages = true